name: walldecor
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  flutter_staggered_grid_view: ^0.7.0
  staggered_grid_view: ^0.0.1
  carousel_slider: ^5.1.1
  flutter_svg: ^2.2.2
  smooth_page_indicator: ^1.0.0+2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.2.1
  http: ^1.6.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  device_info_plus: ^10.1.0
  uuid: ^4.2.1
  equatable: ^2.0.5
  firebase_messaging: ^16.0.4
  in_app_purchase: ^3.2.3
  url_launcher: ^6.3.2
  share_plus: ^12.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
 
  
  flutter_lints: ^5.0.0
flutter:
  assets:
    - assets/images/
    - assets/navbaricons/
    - assets/home/
    - assets/collection/
    - assets/trending/
    - assets/svg/
    
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
