name: walldecor
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  flutter_staggered_grid_view: ^0.7.0
  staggered_grid_view: ^0.0.1
  carousel_slider: ^5.1.1
  flutter_svg: ^2.2.2
  smooth_page_indicator: ^1.0.0+2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.2.1
  http: ^1.2.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  device_info_plus: ^10.1.0
  uuid: ^4.2.1
  equatable: ^2.0.5
  firebase_messaging: ^16.0.4
  in_app_purchase: ^3.2.3
  url_launcher: ^6.3.2
  share_plus: ^12.0.0
  sign_in_with_apple: ^6.1.2
  connectivity_plus: ^7.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.0
  gal: ^2.3.0
  cached_network_image: ^3.4.1
  loading_animation_widget: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
 
  
  flutter_lints: ^5.0.0
flutter:
  assets:
    - assets/images/
    - assets/navbaricons/
    - assets/svg/
  fonts:
    - family: MonaSans
      fonts:
        - asset: assets/fonts/Mona-Sans.ttf
        - asset: assets/fonts/Mona-Sans-Black.ttf
        - asset: assets/fonts/Mona-Sans-BlackItalic.ttf
        - asset: assets/fonts/Mona-Sans-BlackNarrow.ttf
        - asset: assets/fonts/Mona-Sans-BlackWide.ttf
        - asset: assets/fonts/Mona-Sans-BlackWideItalic.ttf
        - asset: assets/fonts/Mona-Sans-Bold.ttf
        - asset: assets/fonts/Mona-Sans-BoldItalic.ttf
        - asset: assets/fonts/Mona-Sans-BoldNarrow.ttf
        - asset: assets/fonts/Mona-Sans-BoldNarrowItalic.ttf
        - asset: assets/fonts/Mona-Sans-BoldWide.ttf
        - asset: assets/fonts/Mona-Sans-BoldWideItalic.ttf
        - asset: assets/fonts/Mona-Sans-ExtraBold.ttf
        - asset: assets/fonts/Mona-Sans-ExtraBoldItalic.ttf
        - asset: assets/fonts/Mona-Sans-ExtraBoldNarrow.ttf
        - asset: assets/fonts/Mona-Sans-ExtraBoldNarrowItalic.ttf
        - asset: assets/fonts/Mona-Sans-ExtraBoldWide.ttf
        - asset: assets/fonts/Mona-Sans-ExtraBoldWideItalic.ttf
        - asset: assets/fonts/Mona-Sans-Light.ttf
        - asset: assets/fonts/Mona-Sans-LightItalic.ttf
        - asset: assets/fonts/Mona-Sans-LightNarrow.ttf
        - asset: assets/fonts/Mona-Sans-LightNarrowItalic.ttf
        - asset: assets/fonts/Mona-Sans-LightWide.ttf
        - asset: assets/fonts/Mona-Sans-LightWideItalic.ttf
        - asset: assets/fonts/Mona-Sans-Medium.ttf
        - asset: assets/fonts/Mona-Sans-MediumItalic.ttf
        - asset: assets/fonts/Mona-Sans-MediumNarrow.ttf
        - asset: assets/fonts/Mona-Sans-MediumNarrowItalic.ttf
        - asset: assets/fonts/Mona-Sans-MediumWide.ttf
        - asset: assets/fonts/Mona-Sans-MediumWideItalic.ttf
        - asset: assets/fonts/Mona-Sans-Regular.ttf
        - asset: assets/fonts/Mona-Sans-RegularItalic.ttf
        - asset: assets/fonts/Mona-Sans-RegularNarrow.ttf
        - asset: assets/fonts/Mona-Sans-RegularNarrowItalic.ttf
        - asset: assets/fonts/Mona-Sans-RegularWide.ttf
        - asset: assets/fonts/Mona-Sans-RegularWideItalic.ttf
        - asset: assets/fonts/Mona-Sans-SemiBold.ttf
        - asset: assets/fonts/Mona-Sans-SemiBoldItalic.ttf
        - asset: assets/fonts/Mona-Sans-SemiBoldNarrow.ttf
        - asset: assets/fonts/Mona-Sans-SemiBoldNarrowItalic.ttf
        - asset: assets/fonts/Mona-Sans-SemiBoldWide.ttf
        - asset: assets/fonts/Mona-Sans-SemiBoldWideItalic.ttf
        - asset: assets/fonts/Mona-Sans-UltraLight.ttf
        - asset: assets/fonts/Mona-Sans-UltraLightItalic.ttf
        - asset: assets/fonts/Mona-Sans-UltraLightNarrow.ttf
        - asset: assets/fonts/Mona-Sans-UltraLightNarrowItalic.ttf
        - asset: assets/fonts/Mona-Sans-UltraLightWide.ttf
        - asset: assets/fonts/Mona-Sans-UltraLightWideItalic.ttf  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
